continuation_prompt = "[▶](bright-green)"

[character]
success_symbol = "[❯❯❯](bold green)"
error_symbol = "[❯❯❯](bold red)"
vicmd_symbol = "[❮❮❮](bold green)"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold blue"

[git_branch]
symbol = "🌱 "

[git_metrics]
disabled = false

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[kubernetes]
disabled = false

[status]
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
disabled = false
